### ISSUE TITLE
TextMeshProのアニメーションで、テキストを変更し再度アニメーションを生成してもうまく生成されない不具合

### ISSUE THREAD

**Issue by AtsuAtsu0120** [AnnulusGames/MagicTween#15]
### 概要
以下のコードを再生すると、２回目のアニメーションが上手く作成されません。
```CSharp
        var list = new List<Tween>();
        for(var i = 0; i < text.GetCharCount(); i++)
        {
	　　　　var tween = text.TweenCharColorAlpha(i, 0, 0.2f).SetInvert().SetDelay(i * 0.2f);
           　　 tween.Play();
            　　list.Add(tween);
	}
        
	await UniTask.WaitUntil(() => !list.Exists(x => x.IsPlaying()));

	text.text = "123456789123456789";
	for (var i = 0; i < text.GetCharCount(); i++)
	{
		var tween = text.TweenCharColorAlpha(i, 0, 0.2f).SetInvert().SetDelay(i * 0.2f);
		tween.Play();
	}
```

※ textはTextMeshProUGUIのインスタンスです。
※ textの既存の文字列は「New Text」です。新しく代入するものよりも短いと２度目がバグるようです。
### 試したこと
- テキストを変更したのち、UniTask.Delayで少し遅延させてからアニメーションを生成する。
- 異なるプロジェクトで同じコードを利用する。

### コメント
さきほど、メンションさせていただいたものです。

もし、そもそもコードが間違っていたらすみません。
ご指導ください。

(2023/10/25 20:42 追記)

**Comment by nuskey8** [comment]
この動作はTextMeshProの仕様によるもので、TMP_Textのtextを変更しても内部のCharacterInfoが更新されないことが要因となっています。(`GetCharCount()`はtextの長さではなくcharacterInfo配列の長さを返す)

そのためTweenの情報を正しく反映させるには、textの変更後にTMP_Textの`ForceMeshUpdate()`を呼んでメッシュを更新する必要があります。

**Comment by AtsuAtsu0120** [comment]
ご返信ありがとうございます。

私もそう思い、`ForceMeshUpdate()`を使って、以下のようにソースコードを変更してデバックをしてみました。（記載し忘れていました。）
しかし、`GetCharCount()`は正しい数字を返すようになるものの、アニメーションは正しく生成されません。

```csharp
var list = new List<Tween>();
for(var i = 0; i < text.GetCharCount(); i++)
{
	var tween = text.TweenCharColorAlpha(i, 0, 0.2f).SetInvert().SetDelay(i * 0.2f);
    tween.Play();
    list.Add(tween);
}

await UniTask.WaitUntil(() => !list.Exists(x => x.IsPlaying()));

text.text = "123456789123456789";
text.ForceMeshUpdate();

for (var i = 0; i < text.GetCharCount(); i++)
{
	var tween = text.TweenCharColorAlpha(i, 0, 0.2f).SetInvert().SetDelay(i * 0.2f);
	tween.Play();
}
```

このコードを初期のテキストが「New Text」（8文字）で実行すると「12345678」（8文字）まで正しく生成され、それ以外の文字は消えて見えます。
9以降の文字はアニメーションが再生されているものの、透明度がフェードしないという挙動をしているように思います。

よろしくお願いします。

**Comment by nuskey8** [comment]
詳細を調査したところ、TextMeshProを操作する箇所に不具合があり正しく動作していないことを確認しました。
先ほど修正版をv0.1.10としてリリースしましたのでご確認いただけると幸いです。

**Comment by AtsuAtsu0120** [comment]
修正を確認できました。

ありがとうございます！！
